[package]
edition = "2018"
name = "mem_reader"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.15.0"
remoteprocess = {version = "0.4.7", features = ["unwind"]}
sysinfo = "0.22.3"
